replicaCount: 1

image:
  repo: registry.gitlab.com/ayerin/mini-node-api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.1.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

healthcheck:
  livenessProbe:
    httpGet:
      path: /healthz
      port: 3000
  readinessProbe:
    httpGet:
      path: /healthz
      port: 3000

service:
  type: ClusterIP
  port: 80
  containerPort: 3000

resources:
  limits:
    cpu: 2500m
    memory: 1Gi
  requests:
    cpu: 1000m
    memory: 256Mi
