apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ printf "%s-%s" .Values.project.name .Values.project.environment }}
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: This project will cover all projects

  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - {{ .Values.repo.url }}

  # Only permit applications to deploy to the namespace in the same cluster
  destinations:
    - namespace: {{ .Values.project.destination.namespace | quote }}
      server: {{ .Values.project.destination.server }}
