apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mini-node-api.fullname" . }}
  labels: {{- include "mini-node-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mini-node-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mini-node-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.healthcheck.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.healthcheck.readinessProbe | nindent 12 }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
